### ISSUE TITLE
Docker hub Team membership restrictions

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cms-docker#121]
Docker hub has changed the "Free Team" for organizations. Now they only allow 1 team of max 3 members. Currently we have 3 teams with more than 3 members each (specially `dmwm` team has 12 members). For now dockerhub has not asked us to cleanup these team but I guess in future they might. Currently we can not add any more teams or members to any of our teams ( we already have 16 seats fill out of 3). 

  For cms images we are using `cmsblddoc`, I would suggest that for `dmwm` you can also start using `dmwmbot` instead of individual accounts.
 
FYI @muhammadimranfarooqi @yuyiguo @ericvaandering  @bbockelm  @vkuznet  @fabioespinosa  @ddaina  @panos512  @goughes  @amaltaro  @todorivanov

**Comment by ericvaandering** [comment]
Just so I understand we'd use a shared account with login? Are you going to contact us with the credentials? dmwmbot sounds like something I might have set up, but I'm not sure. :-)

**Comment by smuzaffar** [comment]
I think @vkuznet has setup the @dmwmbot  and he should have the credentials of it.

**Comment by vkuznet** [comment]
We (me and DMWM L2's) setup dmwmbot docker hub account when setting up CI/CD workflows. Kevin and Katy has credentials and can share with the group. I don't use them directly since all of my stuff now has CI/CD which only requires tokens (therefore I personally don't need to know credentials of the account).

I suggest that whoever needs them will contact DMWM L2's who will eventually maintain them and delegate to next L2's.

**Comment by todor-ivanov** [comment]
Hi @vkuznet , Sorry for the repetition here but just to be on the same page. So for the process of uploading images to the dmwm namespace in docker hub we should all use the `dmwmbot` account. And the username and password are  currently known to the L2s. If so, may I suggest something here, which if I understand correctly will make the process almost identical with the token based authentication you were mentioning above. 

For the sake of uploading the image I do not need to know the password for the account I need to have the `~/.docker/config.json` file produced with the following command: 

```
docker login --username=dmwmbot 
```

Which has the following content:

```
$ cat ~/.docker/config.json 
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "SomeHaSHgoesHere3123413=&$4rn34r"
		}
	}
}
```
I haven't tried  it yet but hope that would work. Not much different than providing the password, though, but would at least facilitate the process of sharing credentials a little bit. And I suppose the end user shouldn't be able to revert the hash back and obtain the password. What do you think?

**Comment by vkuznet** [comment]
@todor-ivanov feel free to explore this option with L2's. I already automated all my workflows and plan to do so for all future repo I'll manage, and therefore I'm free from this issue. The CI/CD github actions uses docker hub token and this is what L2's either give me (when I manage personal repo) or put in place when the repo is under dmwm umbrella. In particular, Katy did that for all dmwm repo (including WMcore). Therefore if you'll setup CI/CD for WMCore you'll already have proper secret in place to upload the images.

**Comment by todor-ivanov** [comment]
Thanks @vkuznet. Actually I think we can benefit from all the good things the token based authentication provides. I just tested the safest possible procedure with my personal account in docker hub, and it seems to be working perfectly find. We do not need to exchange the so generated `.json` config file with the credentials. We are perfectly safe if any of the L2s responsible for the  `dmwmbot` account may generate tokens through the web interface to docker hub as explained here: [1]. Then the only thing the developers need to do in order to generate the config file themselves is to use this token as a password. i.e. [2] This  way the developers do not need to know  the full username and password and they do not have any administrative rights to the account.  

p.s. Upon generation the token should be eventually preserved somewhere by the developer requesting it, because it is not saved anywhere in docker hub.   

FYI: @klannon @amaltaro  @nsmith- @ericvaandering @smuzaffar  @belforte

[1]
https://docs.docker.com/docker-hub/access-tokens/

[2]
```
$ docker login --username dmwmbot --password `cat <path to a token file>`
```

**Comment by belforte** [comment]
Hi @smuzaffar do I have to worry/pay-attention ? I know that I can upload images to cmssw/crab* on dockerhub but have no clue it that means that I am one "or the 12" and/or what's the relation with `dmwmbot`. Is this affecting (only) the images upload done via Jenkins (which I presume means `dmwmbot` also for CRAB).

**Comment by belforte** [comment]
I am confused. in dockerhub there's a cmssw organizaton
https://hub.docker.com/orgs/cmssw
and a dmwm team
https://hub.docker.com/orgs/cmssw/teams/dmwm
both with 12 members (looks the same name but did not check carefully)

Is this cmssw the same as "your" cmssw ?
I do all my docker build and push on cmsdocker01, does it mean that I use the .docker/config.json that you placed there ?
I have a ~belforte/.docker/config.json which I am not sure how was created, but  I guess is not what you talk about here, so how would logging on a different VM make a difference ?

Maybe it is better to leave me confused and you sort this out among people who understand things :-)

**Comment by smuzaffar** [comment]
@cmsdocker you must have run at some point `docker login` on cmsdocker01 which had created the config.json. 

https://hub.docker.com/orgs/cmssw is organization and it has multiple teams 
1. https://hub.docker.com/orgs/cmssw/teams/cmssw : This is used by cmssdt team for pushing `cmssw` container
2. https://hub.docker.com/orgs/cmssw/teams/dmwm : This is used by dmwm team for pushing `dmwm` specific containers . You are member of `dmwm` team :-)

**Comment by belforte** [comment]
thanks @smuzaffar all clear. How careful (wouldn't call it nice) of Docker to prevent me from even seeing the list of teams I am not a member of !

I have no clue how to setup a VM which can use this .docker/config.json for dmwmbot, that's all, does it mean that we will have to log on that machine on the dmwmbot account ? Or can we have a config file in e.g. /etc and point docker to it from any user allowed to log in ? Hopefully @amaltaro or @todor-ivanov can take care and grant us access to that VM ? It would be an overkill (IMHO) to setup a new team just for the 3 people in CRAB land, but if we have to.. I am open.

I do not fully understand the token discussion, am not against innovation, but .docker/config.json does not have a clear text password anyhow, and if I have to keep track of a file, be that a token or a json,. what's the difference in the end ?
To be clear, my .docker/config.json has
```
"auths": {
		"https://index.docker.io/v1/": {
			"auth": "c2JlbGZvcnRlOnBhbGxlLTEyMw=="
		}
```
is that "auth" string a token ? Or what ?
Surely it is not my personal docker account password !

**Comment by smuzaffar** [comment]
@belforte , as you are member of `cmssw` orgnization that is why you are able to see the teams (just like you have cern account and can see all the e-groups even if you are not member of them :-) ) 

We can use the `cmsdocker01` for this purpose. I can create a `dmwmbot` local account there, deploy the `config.json` and allow the DMWM teams members to login as `dmwmbot` (using their public ssh keys).

**Comment by smuzaffar** [comment]
ah please do not share the contents of your .docker/config.json . Although it is not in clear text but any one can use it to push to dockerhub dmwm repos

**Comment by belforte** [comment]
sorry. I am going to update my docker credential.
to be clear: I can **not** see the list of teams. I only see the team I am a member of. This is why I was initially confused.

tech. detail: you can also allow people on a given e-group to log in as dmwmbot on that machine using normal CERN K5 login, no need to maintain ssh keys, all via puppet. We have that in CRAB VM's. Todor knows details.

**Comment by belforte** [comment]
hmm.. indeed in CRAB we we e-group to allow login with CERN username, but to log as a different user we use sudo which will not do here. Sorry. Maybe a .k5login file is easier to maintain than an .shh/authorized_keys ?

**Comment by smuzaffar** [comment]
yes .k5login is much easier to maintain

**Comment by smuzaffar** [comment]
dmwm members who are allowed to use docker on `cmsdocker01` should now be able to ssh as `dmwmbot@cmsdocker01` . the config.json file is still missing for dmwmbot but one of you who has the dmwmbot credential can login to cmsdocker01 and run `docker login`. I can then add the contents of config.json  to puppet (using teigi::secret)

**Comment by todor-ivanov** [comment]
Thank you for the detailed explanations @smuzaffar  and @belforte. As a user for me the membership of an e-group sounds the easiest  to comprehend/use, but as it is more a meter of minimizing maintenance effort here, I am fine with any of the mechanisms for access requests, that may be decided here. 
And since we are on the topic, @smuzaffar, what would be the official order to request such access to `cmsdocker01`?

p.s.
>   but .docker/config.json does not have a clear text password anyhow, and if I have to keep track of a file, be that a token or a json,. what's the difference in the end ?

I cannot tell the difference either, but I checked and for sure the `auth` string in the .json config and the token itself are not equal. Here is what I found with a quick search in the net [1]

[1]
https://stackoverflow.com/questions/43441454/docker-login-auth-token

**Comment by smuzaffar** [comment]
@todor-ivanov , you should be able to login to cmsdocker01 using your cern account. Use your cern account in order to build/upload containers for your personal dockerhub account. For official dmwm containers, you should login as `dmwmbot` (but this will only work once we have its credentials deployed )

**Comment by todor-ivanov** [comment]
Thank you very much @smuzaffar I do confirm I can login to the machine with both my credentials and with `dmwmbot` account.  I will be waiting to hear from you once we have the proper .json configuration file there.  

p.s. Just to mention though. When it comes to the `~/.docker/config.json` file, I just checked and it for sure has the username and password just encoded (but not encrypted) with `base64`. So the following command [1] does reveal the username and password in plain text. So once I saw it I am now a strong supporter of using tokens even for personal configurations, since loosing a .json config wouldn't cost account lost, but only a token which are completely expendable (and tokens provide no administrative rights to the accounts).

[1]
```
$ grep "auth\"\:" ~/.docker/config.json|awk -F \: '{print$2}'| sed -e 's/\("\| \)//g' |base64 --decode
```

**Comment by belforte** [comment]
it is good that files in AFS home are protected, but ok you scared me off .docker/config.json now !

I think someone has to provide the dmwmbot token to Shahzad.  !!

**Comment by todor-ivanov** [comment]
Hii @belforte, that's true AFFS home is protected, but me myself I was also shocked to find such a low level of protection when it comes to storing credentials in a configuration file.

**Comment by todor-ivanov** [comment]
Hi @smuzaffar, We were trying few stuff with Katy @KatyEllis in order to add this token a minute ago and we figured out she was not able to login to the machine cmsdocker01.cern.ch . Can you please take a look.  Thanks!

**Comment by smuzaffar** [comment]
closing this issue as `dmwmbot` has been setup now as a shared account for dmwm team.
